- uses: actions/checkout@v4
  with:
    fetch-depth: 0
    persist-credentials: false   # avoid github-actions[bot] auth

- name: Mirror to personal (verify then push)
  env:
    MIRROR_URL_RAW: ${{ secrets.MIRROR_URL }}
  run: |
    set -euo pipefail
    git config --global --unset-all http.https://github.com/.extraheader || true
    MIRROR_URL=$(printf '%s' "$MIRROR_URL_RAW" | tr -d '\r\n' | sed -e 's/[[:space:]]//g')
    SAFE_URL=$(echo "$MIRROR_URL" | sed -E 's#https://[^@]+@#https://#')
    echo "Will mirror to: $SAFE_URL"
    if ! git ls-remote "$MIRROR_URL" >/dev/null 2>&1; then
      echo "Cannot reach $SAFE_URL"; exit 1; fi
    git remote remove mirror 2>/dev/null || true
    git remote add mirror "$MIRROR_URL"
    git push --mirror mirror
