name: Mirror main to personal repo

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # IMPORTANT: don't inject GITHUB_TOKEN into git config
          persist-credentials: false

      - name: Mirror to personal (verify then push)
        env:
          MIRROR_URL_RAW: ${{ secrets.MIRROR_URL }}
        run: |
          set -euo pipefail
          if [ -z "${MIRROR_URL_RAW:-}" ]; then
            echo "MIRROR_URL is not set; skipping mirror."
            exit 0
          fi

          # Remove any leftover auth header just in case
          git config --global --unset-all http.https://github.com/.extraheader || true

          # Strip hidden whitespace/newlines from the secret
          MIRROR_URL=$(printf '%s' "$MIRROR_URL_RAW" | tr -d '\r\n' | sed -e 's/[[:space:]]//g')

          # Log a safe version (token masked)
          SAFE_URL=$(echo "$MIRROR_URL" | sed -E 's#https://[^@]+@#https://#')
          echo "Will mirror to: $SAFE_URL"

          # Reachability check: 404=bad owner/repo, 401=bad token
          if ! git ls-remote "$MIRROR_URL" >/dev/null 2>&1; then
            echo "Cannot reach $SAFE_URL. Check owner/repo spelling, token scopes, and that the repo exists."
            exit 1
          fi

          git remote remove mirror 2>/dev/null || true
          git remote add mirror "$MIRROR_URL"
          git push mirror --all
          git push mirror --tags
