name: Mirror main to personal repo

on:
  push:
    branches: [ "main" ]  # runs only after merges to main

permissions:
  contents: read

jobs:
  mirror:
    if: ${{ secrets.MIRROR_URL }}  # only runs if the secret is present
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push all refs to mirror
        env:
          MIRROR_URL: ${{ secrets.MIRROR_URL }}
        run: |
          git remote add mirror "$MIRROR_URL"
          git push mirror --all
          git push mirror --tags
