name: Mirror main to personal repo

on:
  push:
    branches: [ "main" ]  # run only after merges to main

permissions:
  contents: read

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to personal (skip if secret missing)
        env:
          MIRROR_URL: ${{ secrets.MIRROR_URL }}
        run: |
          if [ -z "$MIRROR_URL" ]; then
            echo "MIRROR_URL is not set; skipping mirror."
            exit 0
          fi
          git remote remove mirror 2>/dev/null || true
          git remote add mirror "$MIRROR_URL"
          git push mirror --all
          git push mirror --tags
